drop table ROLES if exists;
drop table SENSOR_TYPES if exists;
drop table SENSOR_UNITS if exists;
drop table SENSORS if exists;
drop table USERS if exists;
drop table users_roles if exists;
create table ROLES
(
    role_id integer generated by default as identity,
    name    varchar(255),
    primary key (role_id)
);
create table SENSOR_TYPES
(
    sensor_type_id integer generated by default as identity,
    name           varchar(255),
    primary key (sensor_type_id)
);
create table SENSOR_UNITS
(
    sensor_unit_id integer generated by default as identity,
    name           varchar(255),
    primary key (sensor_unit_id)
);
create table SENSORS
(
    id             bigint generated by default as identity,
    description    varchar(255),
    location       varchar(255),
    model          varchar(255),
    name           varchar(255),
    range_from     integer,
    range_to       integer,
    sensor_type_id integer not null,
    sensor_unit_id integer not null,
    primary key (id),
    foreign key (sensor_unit_id) references SENSOR_UNITS,
    foreign key (sensor_type_id) references SENSOR_TYPES
);
create table USERS
(
    user_id  bigint generated by default as identity,
    enabled  boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (user_id)
);
create table users_roles
(
    role_id integer,
    user_id bigint not null,
    primary key (user_id),
    foreign key (role_id) references ROLES,
    foreign key (user_id) references USERS
);