drop table ROLES if exists;
drop table SENSOR_TYPES if exists;
drop table SENSOR_UNITS if exists;
drop table SENSORS if exists;
drop table USERS if exists;
drop table users_roles if exists;
create table ROLES
(
    role_id integer generated by default as identity,
    name    varchar(255),
    primary key (role_id)
);
create table SENSOR_TYPES
(
    sensor_type_id integer generated by default as identity,
    name           varchar(255),
    primary key (sensor_type_id)
);
create table SENSOR_UNITS
(
    sensor_unit_id integer generated by default as identity,
    name           varchar(255),
    primary key (sensor_unit_id)
);
create table SENSORS
(
    id             bigint generated by default as identity,
    description    varchar(255),
    location       varchar(255),
    model          varchar(255),
    name           varchar(255),
    range_from     integer,
    range_to       integer,
    sensor_type_id integer not null,
    sensor_unit_id integer not null,
    primary key (id)
);
create table USERS
(
    user_id  bigint generated by default as identity,
    enabled  boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (user_id)
);
create table users_roles
(
    role_id integer,
    user_id bigint not null,
    primary key (user_id)
);
alter table ROLES
    add constraint UK_1s6p3xpt8owdb603jky0mo815 unique (name);
alter table SENSOR_TYPES
    add constraint UK_bk5l9p9kl2wr5qnqmtvbpv77t unique (name);
alter table SENSOR_UNITS
    add constraint UK_5fpuqxb6kacaymp796tukw2uy unique (name);
alter table USERS
    add constraint UK_dc4eq7plr20fdhq528twsak1b unique (username);
alter table SENSORS
    add constraint FKbnrhiu15bd6vhkjxja1tbalrs foreign key (sensor_type_id) references SENSOR_TYPES;
alter table SENSORS
    add constraint FKneeq4vqntgxxreo15uop5qc5q foreign key (sensor_unit_id) references SENSOR_UNITS;
alter table users_roles
    add constraint FKh9bs29w8mwo0yc2o3xi7me0nq foreign key (role_id) references ROLES;
alter table users_roles
    add constraint FKn9697al5cfs6rqy40ft93wgc5 foreign key (user_id) references USERS;